using System;
using System.ComponentModel.DataAnnotations;

namespace OCFX.DataModels
{
    /// <summary>
    /// A workout can have many exercises.
    /// Each workout is static and cannot be changed.
    /// </summary>
    public class Workout
    {
        /// <summary>
        /// Standard initialization of a workout
        /// </summary>
        public Workout()
        {
        }

        /// <summary>
        /// Workout initialization with an auto-generated date.
        /// </summary>
        /// <param name="title"></param>
        /// <param name="description"></param>
        /// <param name="duration"></param>
        /// <param name="targetedMuscles"></param>
        public Workout(string title, string description, int duration, WorkoutType targetedMuscles)
        {
            Title = title ?? throw new ArgumentNullException(nameof(title));
            Description = description ?? throw new ArgumentNullException(nameof(description));
            Duration = duration;
            TargetedMuscles = targetedMuscles;
            DateAdded = DateTime.Now;
        }

        [Key]
        [Display(Name = "Workout")]
        public int Id { get; set; }
        /// <summary>
        /// Title of workout
        /// </summary>
        [Display(Name = "Workout Program Title")]
        public string Title { get; set; }
        /// <summary>
        /// Workout Description
        /// </summary>
        [Display(Name = "Workout Description")]
        public string Description { get; set; }
        /// <summary>
        /// Length of time in minutes
        /// </summary>
        [Display(Name = "Workout Duration")]
        public int Duration { get; set; }
        /// <summary>
        /// Targeted muscles for the workout.
        /// </summary>
        [Display(Name = "Target")]
        public WorkoutType TargetedMuscles { get; set; }
        /// <summary>
        /// Date of the workout added. Usually autogenerated.
        /// </summary>
        [Display(Name = "Date Added")]
        [DataType(DataType.Date)]
        public DateTime DateAdded { get; set; }

        /// <summary>
        /// Types of workouts.
        /// Separated by muscle groups.
        /// </summary>
        public enum WorkoutType
        {
            [Display(Name = "Upper Body")]
            UpperBody,
            [Display(Name = "Lower Body")]
            LowerBody,
            [Display(Name = "Total Body")]
            TotalBody,
            [Display(Name = "Chest")]
            Chest,
            [Display(Name = "Back")]
            Back,
            [Display(Name = "Shoulders")]
            Shoulders,
            [Display(Name = "Legs")]
            Legs,
            [Display(Name = "Interval Training")]
            HIIT,
            [Display(Name = "Bodyweight")]
            Bodyweight,
            [Display(Name = "Stretch")]
            Stretch
        }
    }
}